baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableInlineShortcodes = true

[dnb]
[dnb.head]
[dnb.head.styles]
method = 'disabled'

[markup]
[markup.highlight]
noClasses = false

[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'

[[module.imports]]
path = 'github.com/davidsneighbour/hugo-modules/modules/head'
